version: "3"
services:
  web:
    container_name: snippetadmin-web
    image: snippetadmin-web
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "21001:80"
    volumes:
      - ./volumns/web/config.json:/usr/share/nginx/html/config/config.json
      - ./volumns/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumns/web/nginx.conf:/etc/nginx/nginx.conf
  api:    
    container_name: snippetadmin-api
    image: snippetadmin-api
    build: 
      context: ./api
      dockerfile: SnippetAdmin/Dockerfile
    restart: always
    ports:
      - "21002:80"
    environment:
      ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: SkyAPM.Agent.AspNetCore
      SKYWALKING__SERVICENAME: sample_app
    volumes:
      - ./volumns/api/appsettings.json:/app/appsettings.json
      - ./volumns/api/Logs:/app/logs
  database: 
    container_name: snippetadmin-mysql
    image: mysql:8.0.21
    privileged: true
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./volumns/mysql/data:/var/lib/mysql
  