name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd api
        docker build -t ${{ secrets.DOCKER_API_REPOSITORY }}:latest -f ./SnippetAdmin/Dockerfile .
    - name: Login to Ali Registry
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
    - name: Push Image
      run: |
        export tagVersion=$(date +%s)
        docker tag ${{ secrets.DOCKER_API_REPOSITORY }}:latest ${{ secrets.DOCKER_API_REPOSITORY }}:tagVersion
        docker push ${{ secrets.DOCKER_API_REPOSITORY }}:$tagVersion

        
  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env: 
          CI: false
        run: |
          cd web
          docker build -t ${{ secrets.DOCKER_WEB_REPOSITORY }}:latest .
      - name: Login to Ali Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - name: Push Image
        run: |
          export tagVersion=$(date +%s)
          docker tag ${{ secrets.DOCKER_WEB_REPOSITORY }}:latest ${{ secrets.DOCKER_WEB_REPOSITORY }}:tagVersion
          docker push ${{ secrets.DOCKER_WEB_REPOSITORY }}:$tagVersion