name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        cd api
        docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest ./
    - name: Login to Ali Registry
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
    - name: Push Image
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}:$(date +%s)
